#!/usr/bin/env bash
OPTS="
--
C,chain=chain        remote node configuration preset
"
set -e

eval "$(git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?)"

while [[ $1 ]]; do
  case $1 in
    --)              shift; break;;

    -C|--chain)      shift; export SETH_CHAIN=$1;;
    -P|--gas-price)  shift; export ETH_GAS_PRICE=$1;;

    *) printf "${0##*/}: internal error: %q\n" "$1"; exit 1
  esac; shift
done

export SETH_CHAIN=${SETH_CHAIN:-ethlive}
export ETH_GAS_PRICE=${ETH_GAS_PRICE:-30000000000}

case "$SETH_CHAIN" in
  ethlive)
    export ETH_FROM=0x11cCBA532D039ba88B81C6be47d383c50005C729
    export CUP_ID=266
    export DAI_TUB=0x448a5065aebb8e423f0896e6c5d525c040f59af3
    ;;
  kovan)
    export ETH_FROM=da15dce70ab462e66779f23ee14f21d993789ee3
    export CUP_ID=9
    export DAI_TUB=0xa71937147b55deb8a530c7229c442fd3f31b7db2
    ;;
esac

echo $SETH_CHAIN
echo

"${0##*/}-${1-help}" "${@:2}"
