#!/usr/bin/env bash
### cup-gas -- get gas price estimate for transaction in wei
### Usage: cup gas [<safe|average|fast|fastest>] (default: `average')
###
### Gets recommended gas price from https://ethgasstation.info
### Defaults to "average" if no argument given
set -e
type=${1:-average}
case $type in
    safe)                 type="safeLow";;
    average|fast|fastest) type=$type;;
    *) cup --bad-usage "$0"
esac;
echo "Getting $type gas price from ethgasstation..."
json=$(curl -sS "https://ethgasstation.info/json/ethgasAPI.json" 2> /dev/null || true)
gas=$(jshon <<<"$json" -e $type -u 2> /dev/null || true)
[[ $gas ]] || { seth gas-price; exit; }
gas=$(bc <<< "scale=5;${gas} / 10")

seth --to-wei "$gas" gwei
