#!/usr/bin/env bash

for account in $(seth accounts); do
  echo "-----------------------------------------------"
  echo "lad: $account"
  echo
  echo "ETH: $(seth balance $(seth --to-address $account))"
  echo "WETH $(token balance $(dai gem) $account)"
  echo "DAI: $(token balance $(dai dai) $account)"
done
