#!/usr/bin/env bash
set -e

bal=$(token balance $(dai dai) $ETH_FROM)
dai=${1:-$bal}

sig="getBuyAmount(address,address,uint)"
base=$(dai gem)
quote=$(dai dai)
amt=$(seth --to-uint256 $(seth --to-wei "$dai eth"))
rtn=$(seth call $OASIS $sig $base $quote $amt)

if [[ $rtn -eq "0x" ]]; then
  echo "$dai DAI - volume not available"
  exit
fi

fill=$(seth --to-fix 18 $(seth --to-dec $rtn))
price=$(echo "scale=2;$dai / $fill" | bc)

echo "Reference (pip):"
echo "\$$(dai tag) USD/ETH"
echo
echo "Oasis Quote:"
echo
echo "Buy: $fill WETH"
echo "Sell: $dai DAI"
echo "Price: $price DAI/WETH"
